server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: grail-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: grail
          __path__: /var/log/grail/*.log


